# Generated by Django 5.0.1 on 2026-03-15 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я та прізвище")),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Посада')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Назва об'єкта")),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адреса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Об'єкт",
                'verbose_name_plural': "Об'єкти",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='scheduler.employee', verbose_name='Працівник')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='scheduler.site', verbose_name="Об'єкт")),
            ],
            options={
                'verbose_name': 'Чергування',
                'verbose_name_plural': 'Чергування',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
