# Generated by Django 6.0.3 on 2026-03-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Скорочена назва'),
        ),
    ]
