# Generated by Django 6.0.3 on 2026-03-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_site_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name'], 'verbose_name': 'Працівник', 'verbose_name_plural': 'Працівники'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='По-батькові'),
        ),
        migrations.AddField(
            model_name='site',
            name='color',
            field=models.CharField(default='#4f46e5', max_length=7, verbose_name='Колір'),
        ),
        migrations.AddField(
            model_name='site',
            name='display_mode',
            field=models.CharField(choices=[('symbol', 'Символ'), ('color', 'Кольором')], default='symbol', max_length=10, verbose_name='Відображення в календарі'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Посада'),
        ),
    ]
